name: neon_widgets
description: The complete neon solution. This package provides Neon widgets with and without flicker effect.
version: 2.0.0
homepage: https://github.com/ojasjain24/neon_widgets_flutter

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
